# File: D:\Projects\RogueCities\RogueCities_UrbanSpatialDesigner\tools\External_Connect\ollama-gateway\.gateway-run\start-cloudflare-window.ps1
# Auto-generated by start-all-repo-prompt.ps1
# Prints quick tunnel URL and performs a public /health test once URL is detected.
$ErrorActionPreference = 'Stop'

$targetUrl = 'http://127.0.0.1:7077'
$apiKeyDisplay = 'BVhyxOeGAfl2E2DECoeYKi9wZyCp0i03n'
$didPublicTest = $false

Write-Host ('[Cloudflare] Quick tunnel target -> ' + $targetUrl) -ForegroundColor Green
Write-Host ('[Cloudflare] API Key (X-API-Key)  -> ' + $apiKeyDisplay) -ForegroundColor Magenta
Write-Host '[Cloudflare] Waiting for quick tunnel URL...' -ForegroundColor Yellow
Write-Host ''

& cloudflared tunnel --url $targetUrl 2>&1 |
    ForEach-Object {
        $line = $_.ToString()
        Write-Host $line

        if ($line -match 'https://[a-z0-9-]+\.trycloudflare\.com') {
            $url = $Matches[0]

            try {
                Set-Clipboard -Value $url
                $clipMsg = ' (URL copied to clipboard)'
            }
            catch {
                $clipMsg = ''
            }

            Write-Host ''
            Write-Host ('[Cloudflare] Quick Tunnel URL: ' + $url + $clipMsg) -ForegroundColor Magenta
            Write-Host ('[Cloudflare] API Key (X-API-Key): ' + $apiKeyDisplay) -ForegroundColor Magenta
            Write-Host '[Cloudflare] Paste URL into GPT Action base URL + OpenAPI servers[0].url' -ForegroundColor Magenta

            if (-not $didPublicTest) {
                $didPublicTest = $true
                try {
                    $health = Invoke-RestMethod -Method Get -Uri (($url.TrimEnd('/')) + '/health') -Headers @{ 'X-API-Key' = $apiKeyDisplay } -TimeoutSec 20
                    Write-Host ('[Cloudflare] Public /health test: PASS | status=' + $health.status) -ForegroundColor Green
                    if ($null -ne $health.ollama) {
                        Write-Host ('[Cloudflare] Ollama reachability (via gateway): ' + [string]$health.ollama.reachable) -ForegroundColor Green
                    }
                }
                catch {
                    Write-Host ('[Cloudflare] Public /health test: FAIL | ' + $_.Exception.Message) -ForegroundColor Red
                }
            }

            Write-Host ''
        }
    }
