# File: D:\Projects\RogueCities\RogueCities_UrbanSpatialDesigner\tools\External_Connect\ollama-gateway\.gateway-run\start-ollama-window.ps1
# Auto-generated by start-all-repo-prompt.ps1
$ErrorActionPreference = 'Stop'
Write-Host '[Ollama] Starting ollama serve...' -ForegroundColor Green
ollama serve
