# File: D:\Projects\RogueCities\RogueCities_UrbanSpatialDesigner\tools\External_Connect\ollama-gateway\.gateway-run\start-gateway-window.ps1
# Auto-generated by start-all-repo-prompt.ps1
# Expects API_KEY / OLLAMA_BASE / CODE_ROOT in environment (set by parent Start-Process -Environment)
$ErrorActionPreference = 'Stop'

if (-not (Test-Path 'D:\Projects\RogueCities\RogueCities_UrbanSpatialDesigner\tools\External_Connect\ollama-gateway')) {
    Write-Error 'ProjectDir not found: D:\Projects\RogueCities\RogueCities_UrbanSpatialDesigner\tools\External_Connect\ollama-gateway'
    exit 1
}

Set-Location 'D:\Projects\RogueCities\RogueCities_UrbanSpatialDesigner\tools\External_Connect\ollama-gateway'

if (-not (Test-Path 'gateway.py')) {
    Write-Error 'gateway.py not found in D:\Projects\RogueCities\RogueCities_UrbanSpatialDesigner\tools\External_Connect\ollama-gateway'
    exit 1
}

if (-not $env:API_KEY) {
    Write-Error 'API_KEY env var is missing.'
    exit 1
}
if (-not $env:OLLAMA_BASE) {
    Write-Error 'OLLAMA_BASE env var is missing.'
    exit 1
}
if (-not $env:CODE_ROOT) {
    Write-Error 'CODE_ROOT env var is missing.'
    exit 1
}

$k = $env:API_KEY
$fp = if ($k.Length -ge 8) { $k.Substring(0,4) + '...' + $k.Substring($k.Length-4) } else { 'short-key' }

Write-Host '[Gateway] Working dir  = D:\Projects\RogueCities\RogueCities_UrbanSpatialDesigner\tools\External_Connect\ollama-gateway' -ForegroundColor DarkGray
Write-Host '[Gateway] AppTarget    = gateway:app' -ForegroundColor DarkGray
Write-Host '[Gateway] Host:Port    = 0.0.0.0:7077' -ForegroundColor DarkGray
Write-Host ('[Gateway] OLLAMA_BASE  = ' + $env:OLLAMA_BASE) -ForegroundColor DarkGray
Write-Host ('[Gateway] CODE_ROOT    = ' + $env:CODE_ROOT) -ForegroundColor DarkGray
Write-Host ('[Gateway] API_KEY      = ' + $fp) -ForegroundColor DarkGray
Write-Host '[Gateway] Starting uvicorn...' -ForegroundColor Green

if ('py' -eq 'py') {
    & py -m uvicorn 'gateway:app' --host '0.0.0.0' --port 7077
}
else {
    & python -m uvicorn 'gateway:app' --host '0.0.0.0' --port 7077
}
