#pragma once
// Font Awesome 6 icon definitions for RogueCityVisualizer
// Include this header where you need to use icons in ImGui

#include "../third_party/icons/IconsFontAwesome6.h"

// Convenience aliases for commonly used icons in this application
// Tools
#define ICON_TOOL_SELECT ICON_FA_ARROW_POINTER
#define ICON_TOOL_PAN ICON_FA_HAND
#define ICON_TOOL_ROAD ICON_FA_ROAD
#define ICON_TOOL_RIVER ICON_FA_WATER
#define ICON_TOOL_DISTRICT ICON_FA_LAYER_GROUP
#define ICON_TOOL_AXIOM ICON_FA_CROSSHAIRS
#define ICON_TOOL_MEASURE ICON_FA_RULER
#define ICON_TOOL_LOT ICON_FA_BUILDING

// Actions
#define ICON_ACTION_GENERATE ICON_FA_PLAY
#define ICON_ACTION_EXPORT ICON_FA_FILE_EXPORT
#define ICON_ACTION_IMPORT ICON_FA_FILE_IMPORT
#define ICON_ACTION_SAVE ICON_FA_FLOPPY_DISK
#define ICON_ACTION_LOAD ICON_FA_FOLDER_OPEN
#define ICON_ACTION_DELETE ICON_FA_TRASH
#define ICON_ACTION_ADD ICON_FA_PLUS
#define ICON_ACTION_REMOVE ICON_FA_MINUS
#define ICON_ACTION_SETTINGS ICON_FA_GEAR
#define ICON_ACTION_REFRESH ICON_FA_ROTATE
#define ICON_ACTION_CLEAR ICON_FA_XMARK

// UI Elements
#define ICON_UI_EYE ICON_FA_EYE
#define ICON_UI_EYE_SLASH ICON_FA_EYE_SLASH
#define ICON_UI_LOCK ICON_FA_LOCK
#define ICON_UI_UNLOCK ICON_FA_LOCK_OPEN
#define ICON_UI_INFO ICON_FA_CIRCLE_INFO
#define ICON_UI_WARNING ICON_FA_TRIANGLE_EXCLAMATION
#define ICON_UI_ERROR ICON_FA_CIRCLE_XMARK
#define ICON_UI_SUCCESS ICON_FA_CIRCLE_CHECK
#define ICON_UI_EXPAND ICON_FA_CHEVRON_DOWN
#define ICON_UI_COLLAPSE ICON_FA_CHEVRON_UP
#define ICON_UI_LEFT ICON_FA_CHEVRON_LEFT
#define ICON_UI_RIGHT ICON_FA_CHEVRON_RIGHT

// City Elements
#define ICON_CITY_HOUSE ICON_FA_HOUSE
#define ICON_CITY_BUILDING ICON_FA_BUILDING
#define ICON_CITY_CHURCH ICON_FA_CHURCH
#define ICON_CITY_CASTLE ICON_FA_CHESS_ROOK
#define ICON_CITY_TREE ICON_FA_TREE
#define ICON_CITY_SHOP ICON_FA_STORE
#define ICON_CITY_INDUSTRY ICON_FA_INDUSTRY
#define ICON_CITY_LANDMARK ICON_FA_MONUMENT

// District Types
#define ICON_DISTRICT_MARKET ICON_FA_STORE
#define ICON_DISTRICT_KEEP ICON_FA_CHESS_ROOK
#define ICON_DISTRICT_TEMPLE ICON_FA_CHURCH
#define ICON_DISTRICT_HARBOR ICON_FA_ANCHOR
#define ICON_DISTRICT_PARK ICON_FA_TREE
#define ICON_DISTRICT_GATE ICON_FA_DOOR_OPEN
#define ICON_DISTRICT_WELL ICON_FA_DROPLET
