// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::axiom_type_type::AxiomType;
use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Axiom {
    pub id: u32,
    pub axiom_type: AxiomType,
    pub position: Vec2,
    pub radius: f64,
    pub theta: f64,
    pub decay: f64,
    pub is_user_placed: bool,
    pub main_road_points: Vec<Vec2>,
}

impl __sdk::InModule for Axiom {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Axiom`.
///
/// Provides typed access to columns for query building.
pub struct AxiomCols {
    pub id: __sdk::__query_builder::Col<Axiom, u32>,
    pub axiom_type: __sdk::__query_builder::Col<Axiom, AxiomType>,
    pub position: __sdk::__query_builder::Col<Axiom, Vec2>,
    pub radius: __sdk::__query_builder::Col<Axiom, f64>,
    pub theta: __sdk::__query_builder::Col<Axiom, f64>,
    pub decay: __sdk::__query_builder::Col<Axiom, f64>,
    pub is_user_placed: __sdk::__query_builder::Col<Axiom, bool>,
    pub main_road_points: __sdk::__query_builder::Col<Axiom, Vec<Vec2>>,
}

impl __sdk::__query_builder::HasCols for Axiom {
    type Cols = AxiomCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AxiomCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            axiom_type: __sdk::__query_builder::Col::new(table_name, "axiom_type"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            radius: __sdk::__query_builder::Col::new(table_name, "radius"),
            theta: __sdk::__query_builder::Col::new(table_name, "theta"),
            decay: __sdk::__query_builder::Col::new(table_name, "decay"),
            is_user_placed: __sdk::__query_builder::Col::new(table_name, "is_user_placed"),
            main_road_points: __sdk::__query_builder::Col::new(table_name, "main_road_points"),
        }
    }
}

/// Indexed column accessor struct for the table `Axiom`.
///
/// Provides typed access to indexed columns for query building.
pub struct AxiomIxCols {
    pub id: __sdk::__query_builder::IxCol<Axiom, u32>,
}

impl __sdk::__query_builder::HasIxCols for Axiom {
    type IxCols = AxiomIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AxiomIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Axiom {}
