// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::building_type_enum_type::BuildingTypeEnum;
use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Building {
    pub id: u32,
    pub lot_id: u32,
    pub district_id: u32,
    pub building_type: BuildingTypeEnum,
    pub position: Vec2,
    pub rotation_radians: f32,
    pub footprint_area: f32,
    pub suggested_height: f32,
    pub estimated_cost: f32,
    pub generation_serial: u64,
}

impl __sdk::InModule for Building {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Building`.
///
/// Provides typed access to columns for query building.
pub struct BuildingCols {
    pub id: __sdk::__query_builder::Col<Building, u32>,
    pub lot_id: __sdk::__query_builder::Col<Building, u32>,
    pub district_id: __sdk::__query_builder::Col<Building, u32>,
    pub building_type: __sdk::__query_builder::Col<Building, BuildingTypeEnum>,
    pub position: __sdk::__query_builder::Col<Building, Vec2>,
    pub rotation_radians: __sdk::__query_builder::Col<Building, f32>,
    pub footprint_area: __sdk::__query_builder::Col<Building, f32>,
    pub suggested_height: __sdk::__query_builder::Col<Building, f32>,
    pub estimated_cost: __sdk::__query_builder::Col<Building, f32>,
    pub generation_serial: __sdk::__query_builder::Col<Building, u64>,
}

impl __sdk::__query_builder::HasCols for Building {
    type Cols = BuildingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BuildingCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            lot_id: __sdk::__query_builder::Col::new(table_name, "lot_id"),
            district_id: __sdk::__query_builder::Col::new(table_name, "district_id"),
            building_type: __sdk::__query_builder::Col::new(table_name, "building_type"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            rotation_radians: __sdk::__query_builder::Col::new(table_name, "rotation_radians"),
            footprint_area: __sdk::__query_builder::Col::new(table_name, "footprint_area"),
            suggested_height: __sdk::__query_builder::Col::new(table_name, "suggested_height"),
            estimated_cost: __sdk::__query_builder::Col::new(table_name, "estimated_cost"),
            generation_serial: __sdk::__query_builder::Col::new(table_name, "generation_serial"),
        }
    }
}

/// Indexed column accessor struct for the table `Building`.
///
/// Provides typed access to indexed columns for query building.
pub struct BuildingIxCols {
    pub id: __sdk::__query_builder::IxCol<Building, u32>,
}

impl __sdk::__query_builder::HasIxCols for Building {
    type IxCols = BuildingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BuildingIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Building {}
