// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::district_type_type::DistrictType;
use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct District {
    pub id: u32,
    pub district_type: DistrictType,
    pub primary_axiom_id: i32,
    pub border: Vec<Vec2>,
    pub budget_allocated: f32,
    pub projected_population: u32,
    pub desirability: f32,
    pub average_elevation: f32,
    pub generation_serial: u64,
}

impl __sdk::InModule for District {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `District`.
///
/// Provides typed access to columns for query building.
pub struct DistrictCols {
    pub id: __sdk::__query_builder::Col<District, u32>,
    pub district_type: __sdk::__query_builder::Col<District, DistrictType>,
    pub primary_axiom_id: __sdk::__query_builder::Col<District, i32>,
    pub border: __sdk::__query_builder::Col<District, Vec<Vec2>>,
    pub budget_allocated: __sdk::__query_builder::Col<District, f32>,
    pub projected_population: __sdk::__query_builder::Col<District, u32>,
    pub desirability: __sdk::__query_builder::Col<District, f32>,
    pub average_elevation: __sdk::__query_builder::Col<District, f32>,
    pub generation_serial: __sdk::__query_builder::Col<District, u64>,
}

impl __sdk::__query_builder::HasCols for District {
    type Cols = DistrictCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DistrictCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            district_type: __sdk::__query_builder::Col::new(table_name, "district_type"),
            primary_axiom_id: __sdk::__query_builder::Col::new(table_name, "primary_axiom_id"),
            border: __sdk::__query_builder::Col::new(table_name, "border"),
            budget_allocated: __sdk::__query_builder::Col::new(table_name, "budget_allocated"),
            projected_population: __sdk::__query_builder::Col::new(
                table_name,
                "projected_population",
            ),
            desirability: __sdk::__query_builder::Col::new(table_name, "desirability"),
            average_elevation: __sdk::__query_builder::Col::new(table_name, "average_elevation"),
            generation_serial: __sdk::__query_builder::Col::new(table_name, "generation_serial"),
        }
    }
}

/// Indexed column accessor struct for the table `District`.
///
/// Provides typed access to indexed columns for query building.
pub struct DistrictIxCols {
    pub id: __sdk::__query_builder::IxCol<District, u32>,
}

impl __sdk::__query_builder::HasIxCols for District {
    type IxCols = DistrictIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DistrictIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for District {}
