// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::district_type::District;
use super::district_type_type::DistrictType;
use super::vec_2_type::Vec2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `district`.
///
/// Obtain a handle from the [`DistrictTableAccess::district`] method on [`super::RemoteTables`],
/// like `ctx.db.district()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.district().on_insert(...)`.
pub struct DistrictTableHandle<'ctx> {
    imp: __sdk::TableHandle<District>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `district`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DistrictTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DistrictTableHandle`], which mediates access to the table `district`.
    fn district(&self) -> DistrictTableHandle<'_>;
}

impl DistrictTableAccess for super::RemoteTables {
    fn district(&self) -> DistrictTableHandle<'_> {
        DistrictTableHandle {
            imp: self.imp.get_table::<District>("district"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DistrictInsertCallbackId(__sdk::CallbackId);
pub struct DistrictDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DistrictTableHandle<'ctx> {
    type Row = District;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = District> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DistrictInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DistrictInsertCallbackId {
        DistrictInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DistrictInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DistrictDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DistrictDeleteCallbackId {
        DistrictDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DistrictDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DistrictUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DistrictTableHandle<'ctx> {
    type UpdateCallbackId = DistrictUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DistrictUpdateCallbackId {
        DistrictUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DistrictUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `district`,
/// which allows point queries on the field of the same name
/// via the [`DistrictIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.district().id().find(...)`.
pub struct DistrictIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<District, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DistrictTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `district`.
    pub fn id(&self) -> DistrictIdUnique<'ctx> {
        DistrictIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DistrictIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<District> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<District>("district");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<District>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<District>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `District`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait districtQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `District`.
    fn district(&self) -> __sdk::__query_builder::Table<District>;
}

impl districtQueryTableAccess for __sdk::QueryTableAccessor {
    fn district(&self) -> __sdk::__query_builder::Table<District> {
        __sdk::__query_builder::Table::new("district")
    }
}
