// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::generation_stats_type::GenerationStats;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `generation_stats`.
///
/// Obtain a handle from the [`GenerationStatsTableAccess::generation_stats`] method on [`super::RemoteTables`],
/// like `ctx.db.generation_stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.generation_stats().on_insert(...)`.
pub struct GenerationStatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<GenerationStats>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `generation_stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GenerationStatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GenerationStatsTableHandle`], which mediates access to the table `generation_stats`.
    fn generation_stats(&self) -> GenerationStatsTableHandle<'_>;
}

impl GenerationStatsTableAccess for super::RemoteTables {
    fn generation_stats(&self) -> GenerationStatsTableHandle<'_> {
        GenerationStatsTableHandle {
            imp: self.imp.get_table::<GenerationStats>("generation_stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GenerationStatsInsertCallbackId(__sdk::CallbackId);
pub struct GenerationStatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GenerationStatsTableHandle<'ctx> {
    type Row = GenerationStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GenerationStats> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GenerationStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GenerationStatsInsertCallbackId {
        GenerationStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GenerationStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GenerationStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GenerationStatsDeleteCallbackId {
        GenerationStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GenerationStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GenerationStatsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GenerationStatsTableHandle<'ctx> {
    type UpdateCallbackId = GenerationStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GenerationStatsUpdateCallbackId {
        GenerationStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GenerationStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `stats_id` unique index on the table `generation_stats`,
/// which allows point queries on the field of the same name
/// via the [`GenerationStatsStatsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.generation_stats().stats_id().find(...)`.
pub struct GenerationStatsStatsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GenerationStats, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GenerationStatsTableHandle<'ctx> {
    /// Get a handle on the `stats_id` unique index on the table `generation_stats`.
    pub fn stats_id(&self) -> GenerationStatsStatsIdUnique<'ctx> {
        GenerationStatsStatsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("stats_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GenerationStatsStatsIdUnique<'ctx> {
    /// Find the subscribed row whose `stats_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GenerationStats> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GenerationStats>("generation_stats");
    _table.add_unique_constraint::<u64>("stats_id", |row| &row.stats_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GenerationStats>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GenerationStats>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GenerationStats`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait generation_statsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GenerationStats`.
    fn generation_stats(&self) -> __sdk::__query_builder::Table<GenerationStats>;
}

impl generation_statsQueryTableAccess for __sdk::QueryTableAccessor {
    fn generation_stats(&self) -> __sdk::__query_builder::Table<GenerationStats> {
        __sdk::__query_builder::Table::new("generation_stats")
    }
}
