// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::generation_intent_type::GenerationIntent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `generation_intent`.
///
/// Obtain a handle from the [`GenerationIntentTableAccess::generation_intent`] method on [`super::RemoteTables`],
/// like `ctx.db.generation_intent()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.generation_intent().on_insert(...)`.
pub struct GenerationIntentTableHandle<'ctx> {
    imp: __sdk::TableHandle<GenerationIntent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `generation_intent`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GenerationIntentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GenerationIntentTableHandle`], which mediates access to the table `generation_intent`.
    fn generation_intent(&self) -> GenerationIntentTableHandle<'_>;
}

impl GenerationIntentTableAccess for super::RemoteTables {
    fn generation_intent(&self) -> GenerationIntentTableHandle<'_> {
        GenerationIntentTableHandle {
            imp: self.imp.get_table::<GenerationIntent>("generation_intent"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GenerationIntentInsertCallbackId(__sdk::CallbackId);
pub struct GenerationIntentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GenerationIntentTableHandle<'ctx> {
    type Row = GenerationIntent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GenerationIntent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GenerationIntentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GenerationIntentInsertCallbackId {
        GenerationIntentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GenerationIntentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GenerationIntentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GenerationIntentDeleteCallbackId {
        GenerationIntentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GenerationIntentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GenerationIntentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GenerationIntentTableHandle<'ctx> {
    type UpdateCallbackId = GenerationIntentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GenerationIntentUpdateCallbackId {
        GenerationIntentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GenerationIntentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `intent_id` unique index on the table `generation_intent`,
/// which allows point queries on the field of the same name
/// via the [`GenerationIntentIntentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.generation_intent().intent_id().find(...)`.
pub struct GenerationIntentIntentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GenerationIntent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GenerationIntentTableHandle<'ctx> {
    /// Get a handle on the `intent_id` unique index on the table `generation_intent`.
    pub fn intent_id(&self) -> GenerationIntentIntentIdUnique<'ctx> {
        GenerationIntentIntentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("intent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GenerationIntentIntentIdUnique<'ctx> {
    /// Find the subscribed row whose `intent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GenerationIntent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GenerationIntent>("generation_intent");
    _table.add_unique_constraint::<u64>("intent_id", |row| &row.intent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GenerationIntent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GenerationIntent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GenerationIntent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait generation_intentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GenerationIntent`.
    fn generation_intent(&self) -> __sdk::__query_builder::Table<GenerationIntent>;
}

impl generation_intentQueryTableAccess for __sdk::QueryTableAccessor {
    fn generation_intent(&self) -> __sdk::__query_builder::Table<GenerationIntent> {
        __sdk::__query_builder::Table::new("generation_intent")
    }
}
