// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GenerationStats {
    pub stats_id: u64,
    pub serial: u64,
    pub roads_generated: u32,
    pub districts_generated: u32,
    pub lots_generated: u32,
    pub buildings_generated: u32,
    pub generation_time_ms: f32,
    pub timestamp: __sdk::Timestamp,
}

impl __sdk::InModule for GenerationStats {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GenerationStats`.
///
/// Provides typed access to columns for query building.
pub struct GenerationStatsCols {
    pub stats_id: __sdk::__query_builder::Col<GenerationStats, u64>,
    pub serial: __sdk::__query_builder::Col<GenerationStats, u64>,
    pub roads_generated: __sdk::__query_builder::Col<GenerationStats, u32>,
    pub districts_generated: __sdk::__query_builder::Col<GenerationStats, u32>,
    pub lots_generated: __sdk::__query_builder::Col<GenerationStats, u32>,
    pub buildings_generated: __sdk::__query_builder::Col<GenerationStats, u32>,
    pub generation_time_ms: __sdk::__query_builder::Col<GenerationStats, f32>,
    pub timestamp: __sdk::__query_builder::Col<GenerationStats, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for GenerationStats {
    type Cols = GenerationStatsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GenerationStatsCols {
            stats_id: __sdk::__query_builder::Col::new(table_name, "stats_id"),
            serial: __sdk::__query_builder::Col::new(table_name, "serial"),
            roads_generated: __sdk::__query_builder::Col::new(table_name, "roads_generated"),
            districts_generated: __sdk::__query_builder::Col::new(
                table_name,
                "districts_generated",
            ),
            lots_generated: __sdk::__query_builder::Col::new(table_name, "lots_generated"),
            buildings_generated: __sdk::__query_builder::Col::new(
                table_name,
                "buildings_generated",
            ),
            generation_time_ms: __sdk::__query_builder::Col::new(table_name, "generation_time_ms"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
        }
    }
}

/// Indexed column accessor struct for the table `GenerationStats`.
///
/// Provides typed access to indexed columns for query building.
pub struct GenerationStatsIxCols {
    pub stats_id: __sdk::__query_builder::IxCol<GenerationStats, u64>,
}

impl __sdk::__query_builder::HasIxCols for GenerationStats {
    type IxCols = GenerationStatsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GenerationStatsIxCols {
            stats_id: __sdk::__query_builder::IxCol::new(table_name, "stats_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GenerationStats {}
