// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GenerationIntent {
    pub intent_id: u64,
    pub timestamp: __sdk::Timestamp,
    pub client_id: __sdk::Identity,
    pub description: String,
}

impl __sdk::InModule for GenerationIntent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GenerationIntent`.
///
/// Provides typed access to columns for query building.
pub struct GenerationIntentCols {
    pub intent_id: __sdk::__query_builder::Col<GenerationIntent, u64>,
    pub timestamp: __sdk::__query_builder::Col<GenerationIntent, __sdk::Timestamp>,
    pub client_id: __sdk::__query_builder::Col<GenerationIntent, __sdk::Identity>,
    pub description: __sdk::__query_builder::Col<GenerationIntent, String>,
}

impl __sdk::__query_builder::HasCols for GenerationIntent {
    type Cols = GenerationIntentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GenerationIntentCols {
            intent_id: __sdk::__query_builder::Col::new(table_name, "intent_id"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
            client_id: __sdk::__query_builder::Col::new(table_name, "client_id"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
        }
    }
}

/// Indexed column accessor struct for the table `GenerationIntent`.
///
/// Provides typed access to indexed columns for query building.
pub struct GenerationIntentIxCols {
    pub intent_id: __sdk::__query_builder::IxCol<GenerationIntent, u64>,
}

impl __sdk::__query_builder::HasIxCols for GenerationIntent {
    type IxCols = GenerationIntentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GenerationIntentIxCols {
            intent_id: __sdk::__query_builder::IxCol::new(table_name, "intent_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GenerationIntent {}
