// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::lot_type_type::LotType;
use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushLotArgs {
    pub id: u32,
    pub district_id: u32,
    pub lot_type: LotType,
    pub centroid_x: f64,
    pub centroid_y: f64,
    pub boundary: Vec<Vec2>,
    pub area: f32,
    pub access: f32,
    pub exposure: f32,
    pub serviceability: f32,
    pub privacy: f32,
    pub generation_serial: u64,
}

impl From<PushLotArgs> for super::Reducer {
    fn from(args: PushLotArgs) -> Self {
        Self::PushLot {
            id: args.id,
            district_id: args.district_id,
            lot_type: args.lot_type,
            centroid_x: args.centroid_x,
            centroid_y: args.centroid_y,
            boundary: args.boundary,
            area: args.area,
            access: args.access,
            exposure: args.exposure,
            serviceability: args.serviceability,
            privacy: args.privacy,
            generation_serial: args.generation_serial,
        }
    }
}

impl __sdk::InModule for PushLotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_lot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_lot {
    /// Request that the remote module invoke the reducer `push_lot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_lot:push_lot_then`] to run a callback after the reducer completes.
    fn push_lot(
        &self,
        id: u32,
        district_id: u32,
        lot_type: LotType,
        centroid_x: f64,
        centroid_y: f64,
        boundary: Vec<Vec2>,
        area: f32,
        access: f32,
        exposure: f32,
        serviceability: f32,
        privacy: f32,
        generation_serial: u64,
    ) -> __sdk::Result<()> {
        self.push_lot_then(
            id,
            district_id,
            lot_type,
            centroid_x,
            centroid_y,
            boundary,
            area,
            access,
            exposure,
            serviceability,
            privacy,
            generation_serial,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `push_lot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_lot_then(
        &self,
        id: u32,
        district_id: u32,
        lot_type: LotType,
        centroid_x: f64,
        centroid_y: f64,
        boundary: Vec<Vec2>,
        area: f32,
        access: f32,
        exposure: f32,
        serviceability: f32,
        privacy: f32,
        generation_serial: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_lot for super::RemoteReducers {
    fn push_lot_then(
        &self,
        id: u32,
        district_id: u32,
        lot_type: LotType,
        centroid_x: f64,
        centroid_y: f64,
        boundary: Vec<Vec2>,
        area: f32,
        access: f32,
        exposure: f32,
        serviceability: f32,
        privacy: f32,
        generation_serial: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PushLotArgs {
                id,
                district_id,
                lot_type,
                centroid_x,
                centroid_y,
                boundary,
                area,
                access,
                exposure,
                serviceability,
                privacy,
                generation_serial,
            },
            callback,
        )
    }
}
