// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::building_type_enum_type::BuildingTypeEnum;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushBuildingArgs {
    pub id: u32,
    pub lot_id: u32,
    pub district_id: u32,
    pub building_type: BuildingTypeEnum,
    pub pos_x: f64,
    pub pos_y: f64,
    pub rotation_radians: f32,
    pub footprint_area: f32,
    pub suggested_height: f32,
    pub estimated_cost: f32,
    pub generation_serial: u64,
}

impl From<PushBuildingArgs> for super::Reducer {
    fn from(args: PushBuildingArgs) -> Self {
        Self::PushBuilding {
            id: args.id,
            lot_id: args.lot_id,
            district_id: args.district_id,
            building_type: args.building_type,
            pos_x: args.pos_x,
            pos_y: args.pos_y,
            rotation_radians: args.rotation_radians,
            footprint_area: args.footprint_area,
            suggested_height: args.suggested_height,
            estimated_cost: args.estimated_cost,
            generation_serial: args.generation_serial,
        }
    }
}

impl __sdk::InModule for PushBuildingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_building`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_building {
    /// Request that the remote module invoke the reducer `push_building` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_building:push_building_then`] to run a callback after the reducer completes.
    fn push_building(
        &self,
        id: u32,
        lot_id: u32,
        district_id: u32,
        building_type: BuildingTypeEnum,
        pos_x: f64,
        pos_y: f64,
        rotation_radians: f32,
        footprint_area: f32,
        suggested_height: f32,
        estimated_cost: f32,
        generation_serial: u64,
    ) -> __sdk::Result<()> {
        self.push_building_then(
            id,
            lot_id,
            district_id,
            building_type,
            pos_x,
            pos_y,
            rotation_radians,
            footprint_area,
            suggested_height,
            estimated_cost,
            generation_serial,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `push_building` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_building_then(
        &self,
        id: u32,
        lot_id: u32,
        district_id: u32,
        building_type: BuildingTypeEnum,
        pos_x: f64,
        pos_y: f64,
        rotation_radians: f32,
        footprint_area: f32,
        suggested_height: f32,
        estimated_cost: f32,
        generation_serial: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_building for super::RemoteReducers {
    fn push_building_then(
        &self,
        id: u32,
        lot_id: u32,
        district_id: u32,
        building_type: BuildingTypeEnum,
        pos_x: f64,
        pos_y: f64,
        rotation_radians: f32,
        footprint_area: f32,
        suggested_height: f32,
        estimated_cost: f32,
        generation_serial: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PushBuildingArgs {
                id,
                lot_id,
                district_id,
                building_type,
                pos_x,
                pos_y,
                rotation_radians,
                footprint_area,
                suggested_height,
                estimated_cost,
                generation_serial,
            },
            callback,
        )
    }
}
