// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushGenerationStatsArgs {
    pub serial: u64,
    pub roads_generated: u32,
    pub districts_generated: u32,
    pub lots_generated: u32,
    pub buildings_generated: u32,
    pub generation_time_ms: f32,
}

impl From<PushGenerationStatsArgs> for super::Reducer {
    fn from(args: PushGenerationStatsArgs) -> Self {
        Self::PushGenerationStats {
            serial: args.serial,
            roads_generated: args.roads_generated,
            districts_generated: args.districts_generated,
            lots_generated: args.lots_generated,
            buildings_generated: args.buildings_generated,
            generation_time_ms: args.generation_time_ms,
        }
    }
}

impl __sdk::InModule for PushGenerationStatsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_generation_stats`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_generation_stats {
    /// Request that the remote module invoke the reducer `push_generation_stats` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_generation_stats:push_generation_stats_then`] to run a callback after the reducer completes.
    fn push_generation_stats(
        &self,
        serial: u64,
        roads_generated: u32,
        districts_generated: u32,
        lots_generated: u32,
        buildings_generated: u32,
        generation_time_ms: f32,
    ) -> __sdk::Result<()> {
        self.push_generation_stats_then(
            serial,
            roads_generated,
            districts_generated,
            lots_generated,
            buildings_generated,
            generation_time_ms,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `push_generation_stats` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_generation_stats_then(
        &self,
        serial: u64,
        roads_generated: u32,
        districts_generated: u32,
        lots_generated: u32,
        buildings_generated: u32,
        generation_time_ms: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_generation_stats for super::RemoteReducers {
    fn push_generation_stats_then(
        &self,
        serial: u64,
        roads_generated: u32,
        districts_generated: u32,
        lots_generated: u32,
        buildings_generated: u32,
        generation_time_ms: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PushGenerationStatsArgs {
                serial,
                roads_generated,
                districts_generated,
                lots_generated,
                buildings_generated,
                generation_time_ms,
            },
            callback,
        )
    }
}
