// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::road_type_type::RoadType;
use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Road {
    pub id: u32,
    pub road_type: RoadType,
    pub source_axiom_id: i32,
    pub points: Vec<Vec2>,
    pub layer_id: i32,
    pub has_grade_separation: bool,
    pub contains_signal: bool,
    pub contains_crosswalk: bool,
    pub generation_serial: u64,
}

impl __sdk::InModule for Road {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Road`.
///
/// Provides typed access to columns for query building.
pub struct RoadCols {
    pub id: __sdk::__query_builder::Col<Road, u32>,
    pub road_type: __sdk::__query_builder::Col<Road, RoadType>,
    pub source_axiom_id: __sdk::__query_builder::Col<Road, i32>,
    pub points: __sdk::__query_builder::Col<Road, Vec<Vec2>>,
    pub layer_id: __sdk::__query_builder::Col<Road, i32>,
    pub has_grade_separation: __sdk::__query_builder::Col<Road, bool>,
    pub contains_signal: __sdk::__query_builder::Col<Road, bool>,
    pub contains_crosswalk: __sdk::__query_builder::Col<Road, bool>,
    pub generation_serial: __sdk::__query_builder::Col<Road, u64>,
}

impl __sdk::__query_builder::HasCols for Road {
    type Cols = RoadCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoadCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            road_type: __sdk::__query_builder::Col::new(table_name, "road_type"),
            source_axiom_id: __sdk::__query_builder::Col::new(table_name, "source_axiom_id"),
            points: __sdk::__query_builder::Col::new(table_name, "points"),
            layer_id: __sdk::__query_builder::Col::new(table_name, "layer_id"),
            has_grade_separation: __sdk::__query_builder::Col::new(
                table_name,
                "has_grade_separation",
            ),
            contains_signal: __sdk::__query_builder::Col::new(table_name, "contains_signal"),
            contains_crosswalk: __sdk::__query_builder::Col::new(table_name, "contains_crosswalk"),
            generation_serial: __sdk::__query_builder::Col::new(table_name, "generation_serial"),
        }
    }
}

/// Indexed column accessor struct for the table `Road`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoadIxCols {
    pub id: __sdk::__query_builder::IxCol<Road, u32>,
}

impl __sdk::__query_builder::HasIxCols for Road {
    type IxCols = RoadIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoadIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Road {}
