// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::axiom_type::Axiom;
use super::axiom_type_type::AxiomType;
use super::vec_2_type::Vec2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `axiom`.
///
/// Obtain a handle from the [`AxiomTableAccess::axiom`] method on [`super::RemoteTables`],
/// like `ctx.db.axiom()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.axiom().on_insert(...)`.
pub struct AxiomTableHandle<'ctx> {
    imp: __sdk::TableHandle<Axiom>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `axiom`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AxiomTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AxiomTableHandle`], which mediates access to the table `axiom`.
    fn axiom(&self) -> AxiomTableHandle<'_>;
}

impl AxiomTableAccess for super::RemoteTables {
    fn axiom(&self) -> AxiomTableHandle<'_> {
        AxiomTableHandle {
            imp: self.imp.get_table::<Axiom>("axiom"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AxiomInsertCallbackId(__sdk::CallbackId);
pub struct AxiomDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AxiomTableHandle<'ctx> {
    type Row = Axiom;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Axiom> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AxiomInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AxiomInsertCallbackId {
        AxiomInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AxiomInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AxiomDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AxiomDeleteCallbackId {
        AxiomDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AxiomDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AxiomUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AxiomTableHandle<'ctx> {
    type UpdateCallbackId = AxiomUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AxiomUpdateCallbackId {
        AxiomUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AxiomUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `axiom`,
/// which allows point queries on the field of the same name
/// via the [`AxiomIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.axiom().id().find(...)`.
pub struct AxiomIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Axiom, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AxiomTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `axiom`.
    pub fn id(&self) -> AxiomIdUnique<'ctx> {
        AxiomIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AxiomIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Axiom> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Axiom>("axiom");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Axiom>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Axiom>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Axiom`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait axiomQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Axiom`.
    fn axiom(&self) -> __sdk::__query_builder::Table<Axiom>;
}

impl axiomQueryTableAccess for __sdk::QueryTableAccessor {
    fn axiom(&self) -> __sdk::__query_builder::Table<Axiom> {
        __sdk::__query_builder::Table::new("axiom")
    }
}
