// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::building_type::Building;
use super::building_type_enum_type::BuildingTypeEnum;
use super::vec_2_type::Vec2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `building`.
///
/// Obtain a handle from the [`BuildingTableAccess::building`] method on [`super::RemoteTables`],
/// like `ctx.db.building()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.building().on_insert(...)`.
pub struct BuildingTableHandle<'ctx> {
    imp: __sdk::TableHandle<Building>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `building`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BuildingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BuildingTableHandle`], which mediates access to the table `building`.
    fn building(&self) -> BuildingTableHandle<'_>;
}

impl BuildingTableAccess for super::RemoteTables {
    fn building(&self) -> BuildingTableHandle<'_> {
        BuildingTableHandle {
            imp: self.imp.get_table::<Building>("building"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BuildingInsertCallbackId(__sdk::CallbackId);
pub struct BuildingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BuildingTableHandle<'ctx> {
    type Row = Building;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Building> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BuildingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BuildingInsertCallbackId {
        BuildingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BuildingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BuildingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BuildingDeleteCallbackId {
        BuildingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BuildingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BuildingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BuildingTableHandle<'ctx> {
    type UpdateCallbackId = BuildingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BuildingUpdateCallbackId {
        BuildingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BuildingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `building`,
/// which allows point queries on the field of the same name
/// via the [`BuildingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.building().id().find(...)`.
pub struct BuildingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Building, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BuildingTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `building`.
    pub fn id(&self) -> BuildingIdUnique<'ctx> {
        BuildingIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BuildingIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Building> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Building>("building");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Building>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Building>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Building`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait buildingQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Building`.
    fn building(&self) -> __sdk::__query_builder::Table<Building>;
}

impl buildingQueryTableAccess for __sdk::QueryTableAccessor {
    fn building(&self) -> __sdk::__query_builder::Table<Building> {
        __sdk::__query_builder::Table::new("building")
    }
}
