// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::lot_type_type::LotType;
use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Lot {
    pub id: u32,
    pub district_id: u32,
    pub lot_type: LotType,
    pub centroid: Vec2,
    pub boundary: Vec<Vec2>,
    pub area: f32,
    pub access: f32,
    pub exposure: f32,
    pub serviceability: f32,
    pub privacy: f32,
    pub generation_serial: u64,
}

impl __sdk::InModule for Lot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Lot`.
///
/// Provides typed access to columns for query building.
pub struct LotCols {
    pub id: __sdk::__query_builder::Col<Lot, u32>,
    pub district_id: __sdk::__query_builder::Col<Lot, u32>,
    pub lot_type: __sdk::__query_builder::Col<Lot, LotType>,
    pub centroid: __sdk::__query_builder::Col<Lot, Vec2>,
    pub boundary: __sdk::__query_builder::Col<Lot, Vec<Vec2>>,
    pub area: __sdk::__query_builder::Col<Lot, f32>,
    pub access: __sdk::__query_builder::Col<Lot, f32>,
    pub exposure: __sdk::__query_builder::Col<Lot, f32>,
    pub serviceability: __sdk::__query_builder::Col<Lot, f32>,
    pub privacy: __sdk::__query_builder::Col<Lot, f32>,
    pub generation_serial: __sdk::__query_builder::Col<Lot, u64>,
}

impl __sdk::__query_builder::HasCols for Lot {
    type Cols = LotCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LotCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            district_id: __sdk::__query_builder::Col::new(table_name, "district_id"),
            lot_type: __sdk::__query_builder::Col::new(table_name, "lot_type"),
            centroid: __sdk::__query_builder::Col::new(table_name, "centroid"),
            boundary: __sdk::__query_builder::Col::new(table_name, "boundary"),
            area: __sdk::__query_builder::Col::new(table_name, "area"),
            access: __sdk::__query_builder::Col::new(table_name, "access"),
            exposure: __sdk::__query_builder::Col::new(table_name, "exposure"),
            serviceability: __sdk::__query_builder::Col::new(table_name, "serviceability"),
            privacy: __sdk::__query_builder::Col::new(table_name, "privacy"),
            generation_serial: __sdk::__query_builder::Col::new(table_name, "generation_serial"),
        }
    }
}

/// Indexed column accessor struct for the table `Lot`.
///
/// Provides typed access to indexed columns for query building.
pub struct LotIxCols {
    pub id: __sdk::__query_builder::IxCol<Lot, u32>,
}

impl __sdk::__query_builder::HasIxCols for Lot {
    type IxCols = LotIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LotIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Lot {}
