// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::lot_type::Lot;
use super::lot_type_type::LotType;
use super::vec_2_type::Vec2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `lot`.
///
/// Obtain a handle from the [`LotTableAccess::lot`] method on [`super::RemoteTables`],
/// like `ctx.db.lot()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lot().on_insert(...)`.
pub struct LotTableHandle<'ctx> {
    imp: __sdk::TableHandle<Lot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `lot`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LotTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LotTableHandle`], which mediates access to the table `lot`.
    fn lot(&self) -> LotTableHandle<'_>;
}

impl LotTableAccess for super::RemoteTables {
    fn lot(&self) -> LotTableHandle<'_> {
        LotTableHandle {
            imp: self.imp.get_table::<Lot>("lot"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LotInsertCallbackId(__sdk::CallbackId);
pub struct LotDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LotTableHandle<'ctx> {
    type Row = Lot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Lot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LotInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LotInsertCallbackId {
        LotInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LotInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LotDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LotDeleteCallbackId {
        LotDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LotDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LotUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LotTableHandle<'ctx> {
    type UpdateCallbackId = LotUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LotUpdateCallbackId {
        LotUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LotUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `lot`,
/// which allows point queries on the field of the same name
/// via the [`LotIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lot().id().find(...)`.
pub struct LotIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Lot, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LotTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `lot`.
    pub fn id(&self) -> LotIdUnique<'ctx> {
        LotIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LotIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Lot> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Lot>("lot");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Lot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Lot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Lot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait lotQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Lot`.
    fn lot(&self) -> __sdk::__query_builder::Table<Lot>;
}

impl lotQueryTableAccess for __sdk::QueryTableAccessor {
    fn lot(&self) -> __sdk::__query_builder::Table<Lot> {
        __sdk::__query_builder::Table::new("lot")
    }
}
