// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 5836c268a7307f864b33636357b0869ecc40bc0a).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod axiom_table;
pub mod axiom_type;
pub mod axiom_type_type;
pub mod building_table;
pub mod building_type;
pub mod building_type_enum_type;
pub mod clear_axioms_reducer;
pub mod clear_generated_reducer;
pub mod district_table;
pub mod district_type;
pub mod district_type_type;
pub mod generation_intent_table;
pub mod generation_intent_type;
pub mod generation_stats_table;
pub mod generation_stats_type;
pub mod lot_table;
pub mod lot_type;
pub mod lot_type_type;
pub mod place_axiom_reducer;
pub mod push_building_reducer;
pub mod push_district_reducer;
pub mod push_generation_stats_reducer;
pub mod push_lot_reducer;
pub mod push_road_reducer;
pub mod road_table;
pub mod road_type;
pub mod road_type_type;
pub mod vec_2_type;

pub use axiom_table::*;
pub use axiom_type::Axiom;
pub use axiom_type_type::AxiomType;
pub use building_table::*;
pub use building_type::Building;
pub use building_type_enum_type::BuildingTypeEnum;
pub use clear_axioms_reducer::clear_axioms;
pub use clear_generated_reducer::clear_generated;
pub use district_table::*;
pub use district_type::District;
pub use district_type_type::DistrictType;
pub use generation_intent_table::*;
pub use generation_intent_type::GenerationIntent;
pub use generation_stats_table::*;
pub use generation_stats_type::GenerationStats;
pub use lot_table::*;
pub use lot_type::Lot;
pub use lot_type_type::LotType;
pub use place_axiom_reducer::place_axiom;
pub use push_building_reducer::push_building;
pub use push_district_reducer::push_district;
pub use push_generation_stats_reducer::push_generation_stats;
pub use push_lot_reducer::push_lot;
pub use push_road_reducer::push_road;
pub use road_table::*;
pub use road_type::Road;
pub use road_type_type::RoadType;
pub use vec_2_type::Vec2;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ClearAxioms,
    ClearGenerated,
    PlaceAxiom {
        axiom_type: AxiomType,
        pos_x: f64,
        pos_y: f64,
        radius: f64,
        theta: f64,
        decay: f64,
    },
    PushBuilding {
        id: u32,
        lot_id: u32,
        district_id: u32,
        building_type: BuildingTypeEnum,
        pos_x: f64,
        pos_y: f64,
        rotation_radians: f32,
        footprint_area: f32,
        suggested_height: f32,
        estimated_cost: f32,
        generation_serial: u64,
    },
    PushDistrict {
        id: u32,
        district_type: DistrictType,
        primary_axiom_id: i32,
        border: Vec<Vec2>,
        budget_allocated: f32,
        projected_population: u32,
        desirability: f32,
        average_elevation: f32,
        generation_serial: u64,
    },
    PushGenerationStats {
        serial: u64,
        roads_generated: u32,
        districts_generated: u32,
        lots_generated: u32,
        buildings_generated: u32,
        generation_time_ms: f32,
    },
    PushLot {
        id: u32,
        district_id: u32,
        lot_type: LotType,
        centroid_x: f64,
        centroid_y: f64,
        boundary: Vec<Vec2>,
        area: f32,
        access: f32,
        exposure: f32,
        serviceability: f32,
        privacy: f32,
        generation_serial: u64,
    },
    PushRoad {
        id: u32,
        road_type: RoadType,
        source_axiom_id: i32,
        points: Vec<Vec2>,
        layer_id: i32,
        has_grade_separation: bool,
        contains_signal: bool,
        contains_crosswalk: bool,
        generation_serial: u64,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ClearAxioms => "clear_axioms",
            Reducer::ClearGenerated => "clear_generated",
            Reducer::PlaceAxiom { .. } => "place_axiom",
            Reducer::PushBuilding { .. } => "push_building",
            Reducer::PushDistrict { .. } => "push_district",
            Reducer::PushGenerationStats { .. } => "push_generation_stats",
            Reducer::PushLot { .. } => "push_lot",
            Reducer::PushRoad { .. } => "push_road",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::ClearAxioms => {
                __sats::bsatn::to_vec(&clear_axioms_reducer::ClearAxiomsArgs {})
            }
            Reducer::ClearGenerated => {
                __sats::bsatn::to_vec(&clear_generated_reducer::ClearGeneratedArgs {})
            }
            Reducer::PlaceAxiom {
                axiom_type,
                pos_x,
                pos_y,
                radius,
                theta,
                decay,
            } => __sats::bsatn::to_vec(&place_axiom_reducer::PlaceAxiomArgs {
                axiom_type: axiom_type.clone(),
                pos_x: pos_x.clone(),
                pos_y: pos_y.clone(),
                radius: radius.clone(),
                theta: theta.clone(),
                decay: decay.clone(),
            }),
            Reducer::PushBuilding {
                id,
                lot_id,
                district_id,
                building_type,
                pos_x,
                pos_y,
                rotation_radians,
                footprint_area,
                suggested_height,
                estimated_cost,
                generation_serial,
            } => __sats::bsatn::to_vec(&push_building_reducer::PushBuildingArgs {
                id: id.clone(),
                lot_id: lot_id.clone(),
                district_id: district_id.clone(),
                building_type: building_type.clone(),
                pos_x: pos_x.clone(),
                pos_y: pos_y.clone(),
                rotation_radians: rotation_radians.clone(),
                footprint_area: footprint_area.clone(),
                suggested_height: suggested_height.clone(),
                estimated_cost: estimated_cost.clone(),
                generation_serial: generation_serial.clone(),
            }),
            Reducer::PushDistrict {
                id,
                district_type,
                primary_axiom_id,
                border,
                budget_allocated,
                projected_population,
                desirability,
                average_elevation,
                generation_serial,
            } => __sats::bsatn::to_vec(&push_district_reducer::PushDistrictArgs {
                id: id.clone(),
                district_type: district_type.clone(),
                primary_axiom_id: primary_axiom_id.clone(),
                border: border.clone(),
                budget_allocated: budget_allocated.clone(),
                projected_population: projected_population.clone(),
                desirability: desirability.clone(),
                average_elevation: average_elevation.clone(),
                generation_serial: generation_serial.clone(),
            }),
            Reducer::PushGenerationStats {
                serial,
                roads_generated,
                districts_generated,
                lots_generated,
                buildings_generated,
                generation_time_ms,
            } => __sats::bsatn::to_vec(&push_generation_stats_reducer::PushGenerationStatsArgs {
                serial: serial.clone(),
                roads_generated: roads_generated.clone(),
                districts_generated: districts_generated.clone(),
                lots_generated: lots_generated.clone(),
                buildings_generated: buildings_generated.clone(),
                generation_time_ms: generation_time_ms.clone(),
            }),
            Reducer::PushLot {
                id,
                district_id,
                lot_type,
                centroid_x,
                centroid_y,
                boundary,
                area,
                access,
                exposure,
                serviceability,
                privacy,
                generation_serial,
            } => __sats::bsatn::to_vec(&push_lot_reducer::PushLotArgs {
                id: id.clone(),
                district_id: district_id.clone(),
                lot_type: lot_type.clone(),
                centroid_x: centroid_x.clone(),
                centroid_y: centroid_y.clone(),
                boundary: boundary.clone(),
                area: area.clone(),
                access: access.clone(),
                exposure: exposure.clone(),
                serviceability: serviceability.clone(),
                privacy: privacy.clone(),
                generation_serial: generation_serial.clone(),
            }),
            Reducer::PushRoad {
                id,
                road_type,
                source_axiom_id,
                points,
                layer_id,
                has_grade_separation,
                contains_signal,
                contains_crosswalk,
                generation_serial,
            } => __sats::bsatn::to_vec(&push_road_reducer::PushRoadArgs {
                id: id.clone(),
                road_type: road_type.clone(),
                source_axiom_id: source_axiom_id.clone(),
                points: points.clone(),
                layer_id: layer_id.clone(),
                has_grade_separation: has_grade_separation.clone(),
                contains_signal: contains_signal.clone(),
                contains_crosswalk: contains_crosswalk.clone(),
                generation_serial: generation_serial.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    axiom: __sdk::TableUpdate<Axiom>,
    building: __sdk::TableUpdate<Building>,
    district: __sdk::TableUpdate<District>,
    generation_intent: __sdk::TableUpdate<GenerationIntent>,
    generation_stats: __sdk::TableUpdate<GenerationStats>,
    lot: __sdk::TableUpdate<Lot>,
    road: __sdk::TableUpdate<Road>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "axiom" => db_update
                    .axiom
                    .append(axiom_table::parse_table_update(table_update)?),
                "building" => db_update
                    .building
                    .append(building_table::parse_table_update(table_update)?),
                "district" => db_update
                    .district
                    .append(district_table::parse_table_update(table_update)?),
                "generation_intent" => db_update
                    .generation_intent
                    .append(generation_intent_table::parse_table_update(table_update)?),
                "generation_stats" => db_update
                    .generation_stats
                    .append(generation_stats_table::parse_table_update(table_update)?),
                "lot" => db_update
                    .lot
                    .append(lot_table::parse_table_update(table_update)?),
                "road" => db_update
                    .road
                    .append(road_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.axiom = cache
            .apply_diff_to_table::<Axiom>("axiom", &self.axiom)
            .with_updates_by_pk(|row| &row.id);
        diff.building = cache
            .apply_diff_to_table::<Building>("building", &self.building)
            .with_updates_by_pk(|row| &row.id);
        diff.district = cache
            .apply_diff_to_table::<District>("district", &self.district)
            .with_updates_by_pk(|row| &row.id);
        diff.generation_intent = cache
            .apply_diff_to_table::<GenerationIntent>("generation_intent", &self.generation_intent)
            .with_updates_by_pk(|row| &row.intent_id);
        diff.generation_stats = cache
            .apply_diff_to_table::<GenerationStats>("generation_stats", &self.generation_stats)
            .with_updates_by_pk(|row| &row.stats_id);
        diff.lot = cache
            .apply_diff_to_table::<Lot>("lot", &self.lot)
            .with_updates_by_pk(|row| &row.id);
        diff.road = cache
            .apply_diff_to_table::<Road>("road", &self.road)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "axiom" => db_update
                    .axiom
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "building" => db_update
                    .building
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "district" => db_update
                    .district
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "generation_intent" => db_update
                    .generation_intent
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "generation_stats" => db_update
                    .generation_stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "lot" => db_update
                    .lot
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "road" => db_update
                    .road
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "axiom" => db_update
                    .axiom
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "building" => db_update
                    .building
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "district" => db_update
                    .district
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "generation_intent" => db_update
                    .generation_intent
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "generation_stats" => db_update
                    .generation_stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "lot" => db_update
                    .lot
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "road" => db_update
                    .road
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    axiom: __sdk::TableAppliedDiff<'r, Axiom>,
    building: __sdk::TableAppliedDiff<'r, Building>,
    district: __sdk::TableAppliedDiff<'r, District>,
    generation_intent: __sdk::TableAppliedDiff<'r, GenerationIntent>,
    generation_stats: __sdk::TableAppliedDiff<'r, GenerationStats>,
    lot: __sdk::TableAppliedDiff<'r, Lot>,
    road: __sdk::TableAppliedDiff<'r, Road>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Axiom>("axiom", &self.axiom, event);
        callbacks.invoke_table_row_callbacks::<Building>("building", &self.building, event);
        callbacks.invoke_table_row_callbacks::<District>("district", &self.district, event);
        callbacks.invoke_table_row_callbacks::<GenerationIntent>(
            "generation_intent",
            &self.generation_intent,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GenerationStats>(
            "generation_stats",
            &self.generation_stats,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Lot>("lot", &self.lot, event);
        callbacks.invoke_table_row_callbacks::<Road>("road", &self.road, event);
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        axiom_table::register_table(client_cache);
        building_table::register_table(client_cache);
        district_table::register_table(client_cache);
        generation_intent_table::register_table(client_cache);
        generation_stats_table::register_table(client_cache);
        lot_table::register_table(client_cache);
        road_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "axiom",
        "building",
        "district",
        "generation_intent",
        "generation_stats",
        "lot",
        "road",
    ];
}
