// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::axiom_type_type::AxiomType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlaceAxiomArgs {
    pub axiom_type: AxiomType,
    pub pos_x: f64,
    pub pos_y: f64,
    pub radius: f64,
    pub theta: f64,
    pub decay: f64,
}

impl From<PlaceAxiomArgs> for super::Reducer {
    fn from(args: PlaceAxiomArgs) -> Self {
        Self::PlaceAxiom {
            axiom_type: args.axiom_type,
            pos_x: args.pos_x,
            pos_y: args.pos_y,
            radius: args.radius,
            theta: args.theta,
            decay: args.decay,
        }
    }
}

impl __sdk::InModule for PlaceAxiomArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_axiom`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_axiom {
    /// Request that the remote module invoke the reducer `place_axiom` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_axiom:place_axiom_then`] to run a callback after the reducer completes.
    fn place_axiom(
        &self,
        axiom_type: AxiomType,
        pos_x: f64,
        pos_y: f64,
        radius: f64,
        theta: f64,
        decay: f64,
    ) -> __sdk::Result<()> {
        self.place_axiom_then(axiom_type, pos_x, pos_y, radius, theta, decay, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `place_axiom` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_axiom_then(
        &self,
        axiom_type: AxiomType,
        pos_x: f64,
        pos_y: f64,
        radius: f64,
        theta: f64,
        decay: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl place_axiom for super::RemoteReducers {
    fn place_axiom_then(
        &self,
        axiom_type: AxiomType,
        pos_x: f64,
        pos_y: f64,
        radius: f64,
        theta: f64,
        decay: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PlaceAxiomArgs {
                axiom_type,
                pos_x,
                pos_y,
                radius,
                theta,
                decay,
            },
            callback,
        )
    }
}
