// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::district_type_type::DistrictType;
use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushDistrictArgs {
    pub id: u32,
    pub district_type: DistrictType,
    pub primary_axiom_id: i32,
    pub border: Vec<Vec2>,
    pub budget_allocated: f32,
    pub projected_population: u32,
    pub desirability: f32,
    pub average_elevation: f32,
    pub generation_serial: u64,
}

impl From<PushDistrictArgs> for super::Reducer {
    fn from(args: PushDistrictArgs) -> Self {
        Self::PushDistrict {
            id: args.id,
            district_type: args.district_type,
            primary_axiom_id: args.primary_axiom_id,
            border: args.border,
            budget_allocated: args.budget_allocated,
            projected_population: args.projected_population,
            desirability: args.desirability,
            average_elevation: args.average_elevation,
            generation_serial: args.generation_serial,
        }
    }
}

impl __sdk::InModule for PushDistrictArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_district`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_district {
    /// Request that the remote module invoke the reducer `push_district` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_district:push_district_then`] to run a callback after the reducer completes.
    fn push_district(
        &self,
        id: u32,
        district_type: DistrictType,
        primary_axiom_id: i32,
        border: Vec<Vec2>,
        budget_allocated: f32,
        projected_population: u32,
        desirability: f32,
        average_elevation: f32,
        generation_serial: u64,
    ) -> __sdk::Result<()> {
        self.push_district_then(
            id,
            district_type,
            primary_axiom_id,
            border,
            budget_allocated,
            projected_population,
            desirability,
            average_elevation,
            generation_serial,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `push_district` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_district_then(
        &self,
        id: u32,
        district_type: DistrictType,
        primary_axiom_id: i32,
        border: Vec<Vec2>,
        budget_allocated: f32,
        projected_population: u32,
        desirability: f32,
        average_elevation: f32,
        generation_serial: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_district for super::RemoteReducers {
    fn push_district_then(
        &self,
        id: u32,
        district_type: DistrictType,
        primary_axiom_id: i32,
        border: Vec<Vec2>,
        budget_allocated: f32,
        projected_population: u32,
        desirability: f32,
        average_elevation: f32,
        generation_serial: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PushDistrictArgs {
                id,
                district_type,
                primary_axiom_id,
                border,
                budget_allocated,
                projected_population,
                desirability,
                average_elevation,
                generation_serial,
            },
            callback,
        )
    }
}
