// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::road_type_type::RoadType;
use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushRoadArgs {
    pub id: u32,
    pub road_type: RoadType,
    pub source_axiom_id: i32,
    pub points: Vec<Vec2>,
    pub layer_id: i32,
    pub has_grade_separation: bool,
    pub contains_signal: bool,
    pub contains_crosswalk: bool,
    pub generation_serial: u64,
}

impl From<PushRoadArgs> for super::Reducer {
    fn from(args: PushRoadArgs) -> Self {
        Self::PushRoad {
            id: args.id,
            road_type: args.road_type,
            source_axiom_id: args.source_axiom_id,
            points: args.points,
            layer_id: args.layer_id,
            has_grade_separation: args.has_grade_separation,
            contains_signal: args.contains_signal,
            contains_crosswalk: args.contains_crosswalk,
            generation_serial: args.generation_serial,
        }
    }
}

impl __sdk::InModule for PushRoadArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_road`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_road {
    /// Request that the remote module invoke the reducer `push_road` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_road:push_road_then`] to run a callback after the reducer completes.
    fn push_road(
        &self,
        id: u32,
        road_type: RoadType,
        source_axiom_id: i32,
        points: Vec<Vec2>,
        layer_id: i32,
        has_grade_separation: bool,
        contains_signal: bool,
        contains_crosswalk: bool,
        generation_serial: u64,
    ) -> __sdk::Result<()> {
        self.push_road_then(
            id,
            road_type,
            source_axiom_id,
            points,
            layer_id,
            has_grade_separation,
            contains_signal,
            contains_crosswalk,
            generation_serial,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `push_road` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_road_then(
        &self,
        id: u32,
        road_type: RoadType,
        source_axiom_id: i32,
        points: Vec<Vec2>,
        layer_id: i32,
        has_grade_separation: bool,
        contains_signal: bool,
        contains_crosswalk: bool,
        generation_serial: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_road for super::RemoteReducers {
    fn push_road_then(
        &self,
        id: u32,
        road_type: RoadType,
        source_axiom_id: i32,
        points: Vec<Vec2>,
        layer_id: i32,
        has_grade_separation: bool,
        contains_signal: bool,
        contains_crosswalk: bool,
        generation_serial: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PushRoadArgs {
                id,
                road_type,
                source_axiom_id,
                points,
                layer_id,
                has_grade_separation,
                contains_signal,
                contains_crosswalk,
                generation_serial,
            },
            callback,
        )
    }
}
