// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::road_type::Road;
use super::road_type_type::RoadType;
use super::vec_2_type::Vec2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `road`.
///
/// Obtain a handle from the [`RoadTableAccess::road`] method on [`super::RemoteTables`],
/// like `ctx.db.road()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.road().on_insert(...)`.
pub struct RoadTableHandle<'ctx> {
    imp: __sdk::TableHandle<Road>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `road`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RoadTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RoadTableHandle`], which mediates access to the table `road`.
    fn road(&self) -> RoadTableHandle<'_>;
}

impl RoadTableAccess for super::RemoteTables {
    fn road(&self) -> RoadTableHandle<'_> {
        RoadTableHandle {
            imp: self.imp.get_table::<Road>("road"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RoadInsertCallbackId(__sdk::CallbackId);
pub struct RoadDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RoadTableHandle<'ctx> {
    type Row = Road;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Road> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RoadInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoadInsertCallbackId {
        RoadInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RoadInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RoadDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoadDeleteCallbackId {
        RoadDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RoadDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RoadUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RoadTableHandle<'ctx> {
    type UpdateCallbackId = RoadUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RoadUpdateCallbackId {
        RoadUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RoadUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `road`,
/// which allows point queries on the field of the same name
/// via the [`RoadIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.road().id().find(...)`.
pub struct RoadIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Road, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RoadTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `road`.
    pub fn id(&self) -> RoadIdUnique<'ctx> {
        RoadIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RoadIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Road> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Road>("road");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Road>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Road>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Road`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait roadQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Road`.
    fn road(&self) -> __sdk::__query_builder::Table<Road>;
}

impl roadQueryTableAccess for __sdk::QueryTableAccessor {
    fn road(&self) -> __sdk::__query_builder::Table<Road> {
        __sdk::__query_builder::Table::new("road")
    }
}
